#!/usr/bin/env python3
from __future__ import annotations

from collections import defaultdict
from pathlib import Path

SOURCE_ROOT = Path(r"E:\htdocs\httrack\mk3pro\demos.creative-tim.com\material-kit-pro")
OUTPUT = Path(__file__).resolve().parent.parent / "references" / "inventory.md"


def is_noise(path: Path) -> bool:
    raw = path.as_posix()
    parts = set(path.parts)
    if "https_" in raw or "'https_" in raw:
        return True
    if "raw.githubusercontent.com" in raw or "images.unsplash.com" in raw:
        return True
    if "assets" in parts and path.suffix == ".html":
        return True
    return False


def collect(relative_root: str) -> list[str]:
    root = SOURCE_ROOT / relative_root
    files = []
    for path in sorted(root.rglob("*.html")):
        if is_noise(path):
            continue
        files.append(path.relative_to(SOURCE_ROOT).as_posix())
    return files


def section_groups(section_files: list[str]) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for rel in section_files:
        parts = rel.split("/")
        group = parts[1] if len(parts) > 2 else "misc"
        grouped[group].append(rel)
    return dict(sorted(grouped.items()))


def write_inventory() -> None:
    page_files = collect("pages")
    section_files = collect("sections")
    groups = section_groups(section_files)

    lines: list[str] = []
    lines.append("# Material Kit Pro Inventory")
    lines.append("")
    lines.append(f"Source root: `{SOURCE_ROOT}`")
    lines.append("")
    lines.append("Generated by `scripts/build_inventory.py`.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Page templates: {len(page_files)}")
    lines.append(f"- Section templates: {len(section_files)}")
    lines.append(f"- Section groups: {len(groups)}")
    lines.append("")
    lines.append("## Page Templates")
    lines.append("")
    for rel in page_files:
        lines.append(f"- `{rel}`")
    lines.append("")
    lines.append("## Section Templates By Group")
    lines.append("")
    for group, items in groups.items():
        lines.append(f"### {group}")
        lines.append("")
        for rel in items:
            lines.append(f"- `{rel}`")
        lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    write_inventory()
